name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for actions/checkout

jobs:
  terraform:
    runs-on: myrunner

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure Login via OIDC
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
    

  



  
    
               
          
 

    
   
          
