name: Terraform Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for actions/checkout

jobs:
  terraform:
    runs-on: runner1   # apna self-hosted ya GitHub runner

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure Login via OIDC
      - name: Azure Login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



      # Step 4: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan -out=tfplan

   
 
        
  Deployment: 
    runs-on: runner1
    needs: terraform
    environment: dev
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1: Checkout repo
     - name: Checkout repository
       uses: actions/checkout@v3

      # Step 2: Azure Login via OIDC
     - name: Azure Login
       uses: azure/login@v2.3.0
       with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      # Step 4: Terraform Init
     - name: Terraform apply
       run: terraform apply -auto-approve
        

          
          
        
     
    

  



  
    
               
          
 

    
   
          
