name: Terraform Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for actions/checkout

jobs:
  terraform:
    runs-on: myrunner

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Azure Login via OIDC
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
            # creds: ${{ secrets.AZURE_CREDENTIALS }}
             # ClientId of the Azure Service principal created.
          client-id: "1a54f882-3d18-44ef-ad7b-d850c09049f0"
    # TenantId of the Azure Service principal created.
          tenant-id: "a6395b74-f5d3-427b-b4c0-5a918ab2e374"
    # Azure subscriptionId
          subscription-id: "388a2121-d962-4059-8c36-c24d806cad40"
    

  



  
    
               
          
 

    
   
          
