name: "meri pahla workflow"

on:
  push:
    branches: 
      - 'main'
      - 'features/**'
      - 'hotfix/**'

permissions:
  id-token: write   # OIDC token ke liye zaroori
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest   # myrunner ki jagah ubuntu-latest rakho jab tak self-hosted agent na ho
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5   # stable version, tum chahe to latest rakh sakte ho

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Verify Azure Login
        run: az account show

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan


  
    
               
          
 

    
   
          
